# Generated by Django 3.1.2 on 2020-10-28 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Citroen', 'Citroen'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Mercedes', 'Mercedes'), ('Mini', 'Mini'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota'), ('Volvo', 'Volvo'), ('Tesla', 'Tesla')], max_length=20)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Black', 'Black'), ('White', 'White')], max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Wider Tires', 'Wider Tires'), ('High-Performance Coils', 'High-Performance Coils'), ('Larger Anti-Roll Bars', 'Larger Anti-Roll Bars'), ('Chassis Braces', 'Chassis Braces'), ('Larger Diameter Catalyst-Back Exhaust', 'Larger Diameter Catalyst-Back Exhaust'), ('Stiffer Motor Mounts', 'Stiffer Motor Mounts'), ('Performance Seats', 'Performance Seats'), ('High-Temperature Brake Pads', 'High-Temperature Brake Pads'), ('Less Restrictive Cold-Air Intake', 'Less Restrictive Cold-Air Intake'), ('Stainless-Steel Braided Brake Lines', 'Stainless-Steel Braided Brake Lines')], max_length=100)),
                ('price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
