# Generated by Django 3.1.2 on 2020-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201028_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Citroen', 'Citroen'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Mercedes', 'Mercedes'), ('Mini', 'Mini'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota'), ('Volvo', 'Volvo'), ('Tesla', 'Tesla')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='extras',
            field=models.ManyToManyField(blank=True, to='main_app.Extra'),
        ),
    ]
